import { createSlice } from '@reduxjs/toolkit';

const initialBooks = [
  {
  id: '1',
    title: 'Dune',
    author: 'Frank Herbert',
    description: 'Sci-Fi classic about sandworms.',
    category: 'Sci-Fi',
    rating: 4.5,
    popular: true,
  },
  {
    id: '2',
    title: 'Educated',
    author: 'Tara Westover',
    description: 'Memoir about growing up and self-education.',
    category: 'Non-Fiction',
    rating: 4.8,
    popular: true,
  },
  {
    id: '3',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    description: 'Classic novel of American literature.',
    category: 'Fiction',
    rating: 4.7,
    popular: false,
  },
  {
    id: '4',
    title: 'The Martian',
    author: 'Andy Weir',
    description: 'An astronaut stranded on Mars fights for survival.',
    category: 'Sci-Fi',
    rating: 4.6,
    popular: true,
  },
  {
    id: '5',
    title: '1984',
    author: 'George Orwell',
    description: 'A dystopian novel about totalitarian regime.',
    category: 'Fiction',
    rating: 4.9,
    popular: true,
  },
  {
    id: '6',
    title: 'Becoming',
    author: 'Michelle Obama',
    description: 'Memoir of the former First Lady of the United States.',
    category: 'Non-Fiction',
    rating: 4.7,
    popular: false,
  },
  {
    id: '7',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    description: 'A lone astronaut must save humanity from extinction.',
    category: 'Sci-Fi',
    rating: 4.8,
    popular: true,
  },
  {
    id: '8',
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'An easy & proven way to build good habits and break bad ones.',
    category: 'Non-Fiction',
    rating: 4.6,
    popular: true,
  },
  {
    id: '9',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description: 'Story of the fabulously wealthy Jay Gatsby and his love for Daisy.',
    category: 'Fiction',
    rating: 4.4,
    popular: false,
  },
  {
    id: '10',
    title: 'The Left Hand of Darkness',
    author: 'Ursula K. Le Guin',
    description: 'Exploration and identity in a distant planet.',
    category: 'Sci-Fi',
    rating: 4.3,
    popular: false,
  },
  {
    id: '11',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    description: 'A brief history of humankind.',
    category: 'Non-Fiction',
    rating: 4.7,
    popular: true,
  },
  {
    id: '12',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    description: 'Classic tale of love and misunderstanding.',
    category: 'Fiction',
    rating: 4.9,
    popular: true,
  },
  {
    id: '13',
    title: 'The Road',
    author: 'Cormac McCarthy',
    description: 'A post-apocalyptic journey of father and son.',
    category: 'Fiction',
    rating: 4.2,
    popular: false,
  },
  {
    id: '14',
    title: 'Hyperion',
    author: 'Dan Simmons',
    description: 'A science fiction epic with interconnected tales.',
    category: 'Sci-Fi',
    rating: 4.4,
    popular: false,
  },
  {
    id: '15',
    title: 'Factfulness',
    author: 'Hans Rosling',
    description: 'Ten reasons we’re wrong about the world.',
    category: 'Non-Fiction',
    rating: 4.5,
    popular: false,
  },
  {
    id: '16',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    description: 'Vision of a future society controlled by technology.',
    category: 'Fiction',
    rating: 4.6,
    popular: false,
  },
  {
    id: '17',
    title: 'The Dispossessed',
    author: 'Ursula K. Le Guin',
    description: 'Social science fiction telling of two very different worlds.',
    category: 'Sci-Fi',
    rating: 4.5,
    popular: false,
  },
  {
    id: '18',
    title: 'Quiet',
    author: 'Susan Cain',
    description: 'The power of introverts in a world that can’t stop talking.',
    category: 'Non-Fiction',
    rating: 4.4,
    popular: false,
  },
  {
    id: '19',
    title: 'Moby Dick',
    author: 'Herman Melville',
    description: 'The quest for the great white whale.',
    category: 'Fiction',
    rating: 4.1,
    popular: false,
  },
  {
    id: '20',
    title: 'Foundation',
    author: 'Isaac Asimov',
    description: 'A galactic empire faces decay and collapse.',
    category: 'Sci-Fi',
    rating: 4.6,
    popular: true,
  },
];

const booksSlice = createSlice({
  name: 'books',
  initialState: initialBooks,
  reducers: {
    addBook: (state, action) => {
      state.push({
        ...action.payload,
        id: (state.length + 1).toString(),
      });
    },
  },
});

export const { addBook } = booksSlice.actions;
export default booksSlice.reducer;
